version: '3'

services:
  pizza_backend:
    image: pizza_backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/pizza:/app

  pizza-frontend:
    image: pizza-frontend
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - pizza_backend
    volumes:
      - /app/pizza:/app
